### PR TITLE
Update del.xml

### PR DESCRIPTION
**Pull request by PietroLiuzzo**
https://github.com/BetaMasaheft/Documentation/issues/1660

### CODE REVIEW

**Review by SusanneHummel — APPROVED** [review]
Thank you @PietroLiuzzo

**Comment by SusanneHummel** [comment]
Sorry, Pietro, one more issue concering "del"

The images used above are strictly speaking examples for the "Attributes list", that is placed further down on the guidelines page for "del" (https://betamasaheft.eu/Guidelines/?id=del), and demonstarte the meaning of "expunctuation" as defined there (marked with dots, or lines, or encicrled).

The image for Example 1 and Example 2 given at the beginning of the page "del", I once uploaded here: 

https://github.com/BetaMasaheft/Documentation/issues/1571

Maybe this one is better for the provided examples (example 1 and Example 2) which shall make clear the difference between "expunctuated" vs "effaced" and the double usegae of "del"

Make this sense?

**Comment by PietroLiuzzo** [comment]
Please have a look at the page, if it is more clear now. Thanks!

**Comment by SusanneHummel** [comment]
Perfect now! Thanks!

**Pull request merged**
