### PR TITLE
Collation

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by DenisNosnitsin1970** [comment]
- Is it possible to get a normal continuous text version of the document, in whatever form? The one I see in "guidelines/pages" () is very difficult to follow. 
- I have one question: "Sometimes you might also need to describe the position of a
quire using <gi>locus</gi> elements". If i understand right, "locus" is a constituent element and should be there, why "sometimes"? 
- It is pity that someone reduced "To identify a flyleaf quire is frequently not as simple as it appears..." It will not make the task of the encoder simplier.

**Comment by DenisNosnitsin1970** [comment]
Pietro, what kind of captions? Signature+shelfmark and the folio numbers are sufficient?

**Comment by PietroLiuzzo** [comment]
captions for the images in the doc file, which detail what the image depicts

**Comment by DenisNosnitsin1970** [comment]
You can add them approximately at a place when "stub" is mentioned for the first time ("hooked" etc., if it is still retained). 
[Stubs.docx](https://github.com/BetaMasaheft/guidelines/files/4409163/Stubs.docx)

**Comment by thea-m** [comment]
@DenisNosnitsin1970  
 "Sometimes you might also need to describe the position of a
quire using locus elements": I think what is meant is that `<locus>` is used in the text describing the quire in `<note>`, not the general locus element which states the place of the quire in the manuscript. But you are right, it is easily misunderstood and would need an example. I didn't find one now.

The flyleaf explanation got lost in the editing. I added it now.

I am sorry you find the record difficult to read. I'm afraid I can't be of much help in this regard...

**Comment by DenisNosnitsin1970** [comment]
I would say, perhaps it should be mentioned in an explanation as to what is "note" and how you can use "locus". Here the use of "locus" is tacitely implicated (any descriptive information) otherwise it interferes with the way we count leaves in the quire, and with the fact that "locus" is not mentioned above. If you want to keep this information, perhaps a couple of words on the function of "locus" within "item" would be useful, to underline its main usage.

**Comment by PietroLiuzzo** [comment]
With my changes I tried to respond to the points raised by @DenisNosnitsin1970 
For viewing and reading more easily the basic TEI of the guidelines I use the author mode of Oxygen. in Atom this is not possible.

**Comment by PietroLiuzzo** [comment]
I have also given a go to the collation formula which is currently commented out. but I would need an example which has the A and B, the usage of the short formulae we are advertising. if you have one in mind let me know

**Comment by thea-m** [comment]
Thank you @PietroLiuzzo , wonderful edits!

**Comment by DenisNosnitsin1970** [comment]
Thanks, Pietro! On my part, I am also making a few minor edits.

**Comment by DenisNosnitsin1970** [comment]
Dear Pietro and Dorothea, I have made some minor edits (on the whole the text reads smoothly and is very clear). How do we usually call those who work in BM? "Cataloguer" or "encoder"? Dorothea, 
in the string "Sometimes you might need to describe the position of a
          quire using..." i removed "also", but then I realized that the sentence is not quite clear to me (of course, it is clear, but I need to assume, and my assumption will be probably correct. But not every reader will be successful). Can you try to reword it a little bit?

**Comment by PietroLiuzzo** [comment]
I would probably go for encoders, but well, here they are more or less synonims. we have to try and keep in mind that these guidelines should be fine for use also for encoding data which does not end up in BM.

**Comment by thea-m** [comment]
I wonder now whether the"Sometimes you might need to describe the position" paragraph is necessary anymore. It should be clear from the preceding paragraph that information of any kind should be inside a `<note>`. It was probably originally introduced to the guidelines after a very specific use of locus elements that I cannot reconstruct anymore.

**Comment by DenisNosnitsin1970** [comment]
It is not my line :) You are right, as such it is not essential. The example used in it can be added to examples as to how "note" can be used. Please look at the string: 
note
           Quire 2: 2, stub after 8 9, stub after 1
         item
I think "Quire 2:" should not be here.

**Comment by thea-m** [comment]
It is like this in EMIP01992, which was the example kindly found by Pietro. I didn't follow their particular collation discussions, therefore I wouldn't edit their record now.

**Comment by PietroLiuzzo** [comment]
This has been pending long enough not to require further changes which cannot be another PR. It was a lot of good work, thanks!

**Pull request merged**
