### PR TITLE
EMML EMIP repository clarification

### PR DESCRIPTION
**Pull request by thea-m**
see
https://github.com/BetaMasaheft/Documentation/issues/1099

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
very useful clarification indeed! Thanks!

**Comment by eu-genia** [comment]
I am not sure I understand the example provided

**Comment by thea-m** [comment]
@eu-genia It is EMML6952, which is kept at the institution I indicated in `<repository>`. I just updated it, since we didn't yet have an example. What exactly don't you understand? I'm happy to improve the encoding.

**Comment by eu-genia** [comment]
the text of the guidelines now mentions the bm IDs of the collections (INS0332EMML) - I think this is confusing, as no actual link is provided, I would harmonize this (either we give a @corresp within the collection tag - but then also for E-S mss which we did not do - or leave out the mentions of the IDs in the guidelines)

all EMML manuscripts actually have the primary IES ID (C3–IV-xxx or similar) - would be important to identify these and provide them too (these are shelf marks truly of the manuscripts and not of the copies)

**Comment by PietroLiuzzo** [comment]
your second point can be added as a further specification, but is already said in "all shelfmarks should of course be given".

I do not understand your first point, where do the guidelines mention the "bm ids of the collections"? There is no such thing as an id for a collection in BM. I consequently not understand what the armonization (here in the guidelines? in the data?) would be.

**Comment by eu-genia** [comment]
I meant in the guidelines that now read
```
 The reference to <ref target="INS0332EMML" type="bm">EMML</ref> and <ref target="INS0447EMIP" type="bm">EMIP</ref>
                should remain in <gi>collection</gi>
```

**Comment by PietroLiuzzo** [comment]
Please could you unpack this in a concrete proposal on how this paragraph should be changed? thanks

**Comment by thea-m** [comment]
Do you mean it should be changed to "`The reference to EMML and EMIP should remain in <gi>collection</gi>`"

**Comment by eu-genia** [comment]
I think that would be better, yes :)

**Comment by thea-m** [comment]
And how can the IES ID be found? I don't see it in the catalogues or the form at the beginning of the photographed manuscripts. Is there a list somewhere?
image
Is it this RR 12:1?

**Comment by eu-genia** [comment]
I don't think so, this is a number I can see on many of the EMML cards, but I am not sure, I guess in this case the census number was not registered or is not there

**Pull request merged**
